### ISSUE TITLE
[BUG] Missing confirmation dialog after creating a playbook

### ISSUE THREAD

**Issue by katierik** [RedHatInsights/compliance-frontend#143]
There is no confirmation notification after creating a Playbook in Compliance. 

**To reproduce:**
Remediate from a system detail
See that there is no notification

**Desired behavior:**
Vulnerability app works correctly
The desired behavior can also be seen in this mock: https://redhat.invisionapp.com/share/SNRPBZPVHUR

**Comment by dLobatog** [comment]
@katierik There is a notification now, it was merged 2 days ago https://github.com/RedHatInsights/compliance-frontend/pull/139
