### ISSUE TITLE
Use compliance detail from FE components

### ISSUE THREAD

**Issue by karelhala** [RedHatInsights/compliance-frontend#54]
Use [`SystemDetails`](https://github.com/RedHatInsights/insights-frontend-components/blob/master/src/SmartComponents/Inventory/applications/compliance/Compliance.js) from FE components and change them if needed so we don't have duplicate code and we stay aligned at both compliance, inventory and eventually every application that would like to use such detail.

**Comment by karelhala** [comment]
ping @dLobatog

**Comment by dLobatog** [comment]
https://github.com/RedHatInsights/compliance-frontend/pull/81
